name: Download File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download File Action
  # You may pin to the exact commit or the version.
  # uses: Minionguyjpro/Download-File-Action@cb86d3ecd4ed8bc49f63cf4b33d957c50fcb5ba0
      uses: Minionguyjpro/Download-File-Action@v1
      with:
    # URL to download file from
        url: https://publicfiles.fcc.gov/tv-profile/wjla-tv/political-files/2025/9c611ad9-e211-385b-ccea-57d308125d36
    # Path to store output file
        
          
